### PR TITLE
ENH: add a fieldtrip friendly layout file

### PR DESCRIPTION
**Pull request by robince**
I slightly modified the layout file so it would work with FieldTrip without errors

I removed the space in the channel description and removed the first line. I hope this is correct. I am not used to working with a joint magnetometer + gradiometer setup so I am not sure - but at least I can do basic plots in fieldtrip with this layout.

### CODE REVIEW

**Comment by emanuele** [comment]
Hi,
The original layout file is as shipped by Elekta and FieldTrip, as far as I know. For this reason, I'd prefer to stick with that version. Could it be possible to handle the FieldTrip error, that you are experiencing, within the code instead of modifying the layout file?

**Comment by robince** [comment]
I'm not sure. The main problem I think is the channel labels in the layout (with a space) not matching those in the fieldtrip load script (without a space). I am not sure if fieldtrip would support channel labels containing a space. Removing those spaces and the first line was the only changes I made.

**Comment by emanuele** [comment]
This is unexpected. I want to look into that in detail and double-check where that file originates. I took it from the mne-python project and they told me it was from Elekta or FieldTrip. So I will ask more details to them and will get back to you in a short time.

**Comment by robince** [comment]
No problem... as I say it is working for me now, I just contributed the change in case it is useful to others. There way well be other ways to get it workign (eg changing the load script to use spaces in the channel names) but this was the first thing I tried and it worked for me.

**Comment by agramfort** [comment]
looks good. fieldtrip indeed uses the .lay files and not the .lout file. MNE-Python can read both though.

**Comment by emanuele** [comment]
OK, so it is just a question of format, i.e. .lout vs .lay. At this point I am fine with both files and since the lout has been used by others, I am not removing it. So I am keeping both of them. Thanks.

**Pull request merged**
