### PR TITLE
BUG: load data into 'data' structure

### PR DESCRIPTION
**Pull request by robince**
Had a minor problem converting the data to fieldtrip format which is fixed in this commit.

### CODE REVIEW

**Comment by emanuele** [comment]
Hi,
Thank you for your pull-request. I can test it on Monday and then I'll get back to you.

**Comment by emanuele** [comment]
Hi, my Matlab-expert colleague tells me that it is not necessary to define the "data" variable as you do in commit 0a20a2f. Is there a specific reason for adding it? The Matlab reference manual seems to agree with him: http://www.mathworks.it/it/help/matlab/ref/load.html .

**Comment by robince** [comment]
It is not necessary because of Matlab - it is necessary because later in the script you refer to variables as if it was loaded into a structure.
ie lines 11, 14, 16, 19, 20 etc. refer to a 'data.' structure, which does not exist without my change.

One could just load into the workspace as you suggest, but then those other lines would need to be changed. I made this change as it was smaller and I think it is neater than loading into the workspace (ie if a file is missing one of the required variables it would result in an error because it would be missing from the struct, rather than silently using the version from the previous iteration if it was using load without assigning the output.

**Comment by emanuele** [comment]
I'll ask my colleague to join this conversation. He's in charge of the Matlab part - not me, luckily ;) . Anyway I see you point now (sorry for not having inspected the convert2ft.m file immediately).

**Comment by smkia** [comment]
Thank you for your contribution Robin,
Sorry for the problem, you are right. We will accept your pull request
soon. It seems there are some changes in data structure form last time I
checked my code on the data (Previously the fields were stored in a
structure called "data" which was more reasonable by the way).

**Comment by emanuele** [comment]
OK, even though he's far away in Iceland ;) Mosi was very quick to answer. Thanks. Anyway I am stalling the merge still a bit because of the second commit, db85633, about the Vectorview-all.lout file, which is on a different topic but in the same PR.

**Comment by robince** [comment]
Sorry I tried to make them separate PRs... I have sent a fresh PR from a clean branch with just this change.

Actually I much prefer not having the data nested in additional structure - it allows one to see what variables are there (eg with whos -file) and to memory map to load only the required variables much more easily! :)

**Pull request closed without merging**
